--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admin_data; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admin_data (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    quiz_summary_id bigint NOT NULL
);


ALTER TABLE public.admin_data OWNER TO postgres;

--
-- Name: admin_data_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.admin_data_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.admin_data_id_seq OWNER TO postgres;

--
-- Name: admin_data_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.admin_data_id_seq OWNED BY public.admin_data.id;


--
-- Name: quiz_summary; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quiz_summary (
    quiz_summary_id bigint NOT NULL,
    user_id bigint NOT NULL,
    total_time_taken integer NOT NULL,
    total_score integer NOT NULL,
    "timestamp" timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.quiz_summary OWNER TO postgres;

--
-- Name: quiz_summary_quiz_summary_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.quiz_summary_quiz_summary_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.quiz_summary_quiz_summary_id_seq OWNER TO postgres;

--
-- Name: quiz_summary_quiz_summary_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.quiz_summary_quiz_summary_id_seq OWNED BY public.quiz_summary.quiz_summary_id;


--
-- Name: responses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.responses (
    response_id bigint NOT NULL,
    user_id bigint NOT NULL,
    question_id integer NOT NULL,
    selected_option character varying(255) NOT NULL,
    correct_answer character varying(255) NOT NULL,
    is_correct boolean NOT NULL,
    "timestamp" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    time_taken integer NOT NULL
);


ALTER TABLE public.responses OWNER TO postgres;

--
-- Name: responses_response_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.responses_response_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.responses_response_id_seq OWNER TO postgres;

--
-- Name: responses_response_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.responses_response_id_seq OWNED BY public.responses.response_id;


--
-- Name: user_quiz_summary; Type: TABLE; Schema: public; Owner: fcapp
--

CREATE TABLE public.user_quiz_summary (
    id integer NOT NULL,
    "timestamp" timestamp(6) without time zone,
    total_score integer NOT NULL,
    total_time_taken integer NOT NULL,
    user_email character varying(255)
);


ALTER TABLE public.user_quiz_summary OWNER TO fcapp;

--
-- Name: user_quiz_summary_id_seq; Type: SEQUENCE; Schema: public; Owner: fcapp
--

ALTER TABLE public.user_quiz_summary ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_quiz_summary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    dob date NOT NULL,
    age character varying(255) NOT NULL,
    gender character varying(255) NOT NULL,
    nature_of_work character varying(255) NOT NULL,
    institution character varying(255) NOT NULL,
    department character varying(255) NOT NULL,
    years_experience character varying(255) NOT NULL,
    city character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    id bigint NOT NULL,
    current_question_index integer NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.users_id_seq OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.user_id;


--
-- Name: users_id_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin_data id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin_data ALTER COLUMN id SET DEFAULT nextval('public.admin_data_id_seq'::regclass);


--
-- Name: quiz_summary quiz_summary_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_summary ALTER COLUMN quiz_summary_id SET DEFAULT nextval('public.quiz_summary_quiz_summary_id_seq'::regclass);


--
-- Name: responses response_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.responses ALTER COLUMN response_id SET DEFAULT nextval('public.responses_response_id_seq'::regclass);


--
-- Name: users user_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users ALTER COLUMN user_id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Data for Name: admin_data; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.admin_data (id, user_id, quiz_summary_id) FROM stdin;
\.


--
-- Data for Name: quiz_summary; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quiz_summary (quiz_summary_id, user_id, total_time_taken, total_score, "timestamp") FROM stdin;
\.


--
-- Data for Name: responses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.responses (response_id, user_id, question_id, selected_option, correct_answer, is_correct, "timestamp", time_taken) FROM stdin;
\.


--
-- Data for Name: user_quiz_summary; Type: TABLE DATA; Schema: public; Owner: fcapp
--

COPY public.user_quiz_summary (id, "timestamp", total_score, total_time_taken, user_email) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (user_id, name, email, dob, age, gender, nature_of_work, institution, department, years_experience, city, created_at, id, current_question_index) FROM stdin;
\.


--
-- Name: admin_data_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.admin_data_id_seq', 1, false);


--
-- Name: quiz_summary_quiz_summary_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.quiz_summary_quiz_summary_id_seq', 1, false);


--
-- Name: responses_response_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.responses_response_id_seq', 1, false);


--
-- Name: user_quiz_summary_id_seq; Type: SEQUENCE SET; Schema: public; Owner: fcapp
--

SELECT pg_catalog.setval('public.user_quiz_summary_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- Name: users_id_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq1', 1, false);


--
-- Name: admin_data admin_data_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin_data
    ADD CONSTRAINT admin_data_pkey PRIMARY KEY (id);


--
-- Name: quiz_summary quiz_summary_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_summary
    ADD CONSTRAINT quiz_summary_pkey PRIMARY KEY (quiz_summary_id);


--
-- Name: responses responses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.responses
    ADD CONSTRAINT responses_pkey PRIMARY KEY (response_id);


--
-- Name: admin_data unique_user_quiz_summary; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin_data
    ADD CONSTRAINT unique_user_quiz_summary UNIQUE (user_id, quiz_summary_id);


--
-- Name: user_quiz_summary user_quiz_summary_pkey; Type: CONSTRAINT; Schema: public; Owner: fcapp
--

ALTER TABLE ONLY public.user_quiz_summary
    ADD CONSTRAINT user_quiz_summary_pkey PRIMARY KEY (id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: admin_data admin_data_quiz_summary_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin_data
    ADD CONSTRAINT admin_data_quiz_summary_id_fkey FOREIGN KEY (quiz_summary_id) REFERENCES public.quiz_summary(quiz_summary_id) ON DELETE CASCADE;


--
-- Name: admin_data admin_data_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin_data
    ADD CONSTRAINT admin_data_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: quiz_summary fk_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quiz_summary
    ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- Name: responses fk_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.responses
    ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

